#!/usr/bin/perl

# Menu generated by menutray

# DO NOT edit this file!
# Any change in this file will be lost!
# Edit /home/swampyx/.config/menutray/schema.pl instead!

use Gtk2 ('-init');

my $menu = 'Gtk2::Menu'->new;
my $icon = 'Gtk2::StatusIcon'->new;

$icon->set_from_icon_name('start-here');
$icon->set_visible(1);
$icon->signal_connect('button-release-event', \&show_icon_menu);
$icon->set_tooltip('Click for menu...');

load_menu();

sub show_icon_menu {
    $menu->popup(undef, undef, sub {return Gtk2::StatusIcon::position_menu($menu, 0, 0, $icon)}, [1, 1], 0, 0);
    return 1;
}

sub load_menu {
{
    my $item_pcmanfm_2649 = 'Gtk2::ImageMenuItem'->new("File\ Manager");
    $item_pcmanfm_2649->set_image('Gtk2::Image'->new_from_icon_name("file\-manager",q{menu}));
    $item_pcmanfm_2649->signal_connect('activate', sub {system "pcmanfm &"});
    $menu->append($item_pcmanfm_2649);
}

{
    my $item_sakura_9169 = 'Gtk2::ImageMenuItem'->new("Terminal");
    $item_sakura_9169->set_image('Gtk2::Image'->new_from_icon_name("terminal",q{menu}));
    $item_sakura_9169->signal_connect('activate', sub {system "sakura &"});
    $menu->append($item_sakura_9169);
}

{
    my $item_luakit_9367 = 'Gtk2::ImageMenuItem'->new("Luakit");
    $item_luakit_9367->set_image('Gtk2::Image'->new_from_icon_name("luakit",q{menu}));
    $item_luakit_9367->signal_connect('activate', sub {system "luakit &"});
    $menu->append($item_luakit_9367);
}

{
    my $item_gtk_youtube_viewer_4144 = 'Gtk2::ImageMenuItem'->new("GTK\ Youtube\ Viewer");
    $item_gtk_youtube_viewer_4144->set_image('Gtk2::Image'->new_from_icon_name("gtk\-youtube\-viewer",q{menu}));
    $item_gtk_youtube_viewer_4144->signal_connect('activate', sub {system "gtk\-youtube\-viewer &"});
    $menu->append($item_gtk_youtube_viewer_4144);
}


    $menu->append('Gtk2::SeparatorMenuItem'->new);

    # # # # # # # # # # # # # # # # # # # # ACCESSORIES # # # # # # # # # # # # # # # # # # # # 
{
    my $apps = 'Gtk2::Menu'->new;
    my $category_1 = 'Gtk2::ImageMenuItem'->new("Accessories");
    $category_1->set_image('Gtk2::Image'->new_from_icon_name("applications\-utilities",q{menu}));
{
    my $app_7_zip_fm_3364 = 'Gtk2::ImageMenuItem'->new("7\-Zip\ FM");
    $app_7_zip_fm_3364->signal_connect('activate', sub {system "7zFM &"});
    $app_7_zip_fm_3364->set_property('tooltip_text', "");
    $app_7_zip_fm_3364->set_image('Gtk2::Image'->new_from_icon_name("p7zip",q{menu}));
    $apps->append($app_7_zip_fm_3364);
}
{
    my $app_archive_manager_6754 = 'Gtk2::ImageMenuItem'->new("Archive\ Manager");
    $app_archive_manager_6754->signal_connect('activate', sub {system "file\-roller &"});
    $app_archive_manager_6754->set_property('tooltip_text', "Create\ and\ modify\ an\ archive");
    $app_archive_manager_6754->set_image('Gtk2::Image'->new_from_icon_name("file\-roller",q{menu}));
    $apps->append($app_archive_manager_6754);
}
{
    my $app_leafpad_1563 = 'Gtk2::ImageMenuItem'->new("Leafpad");
    $app_leafpad_1563->signal_connect('activate', sub {system "leafpad &"});
    $app_leafpad_1563->set_property('tooltip_text', "Simple\ text\ editor");
    $app_leafpad_1563->set_image('Gtk2::Image'->new_from_icon_name("leafpad",q{menu}));
    $apps->append($app_leafpad_1563);
}
    $category_1->set_submenu($apps);
    $menu->append($category_1);
}

    # # # # # # # # # # # # # # # # # # # # DEVELOPMENT # # # # # # # # # # # # # # # # # # # # 
{
    my $apps = 'Gtk2::Menu'->new;
    my $category_2 = 'Gtk2::ImageMenuItem'->new("Development");
    $category_2->set_image('Gtk2::Image'->new_from_icon_name("applications\-development",q{menu}));
{
    my $app_geany_8394 = 'Gtk2::ImageMenuItem'->new("Geany");
    $app_geany_8394->signal_connect('activate', sub {system "geany &"});
    $app_geany_8394->set_property('tooltip_text', "A\ fast\ and\ lightweight\ IDE\ using\ GTK2");
    $app_geany_8394->set_image('Gtk2::Image'->new_from_icon_name("geany",q{menu}));
    $apps->append($app_geany_8394);
}
{
    my $app_meld_8990 = 'Gtk2::ImageMenuItem'->new("Meld");
    $app_meld_8990->signal_connect('activate', sub {system "meld &"});
    $app_meld_8990->set_property('tooltip_text', "Compare\ and\ merge\ your\ files");
    $app_meld_8990->set_image('Gtk2::Image'->new_from_icon_name("meld",q{menu}));
    $apps->append($app_meld_8990);
}
{
    my $app_qt4_assistant_2649 = 'Gtk2::ImageMenuItem'->new("Qt4\ Assistant");
    $app_qt4_assistant_2649->signal_connect('activate', sub {system "assistant\-qt4 &"});
    $app_qt4_assistant_2649->set_property('tooltip_text', "Shows\ Qt4\ documentation\ and\ examples");
    $app_qt4_assistant_2649->set_image('Gtk2::Image'->new_from_icon_name("assistant\-qt4",q{menu}));
    $apps->append($app_qt4_assistant_2649);
}
{
    my $app_qt4_designer_5706 = 'Gtk2::ImageMenuItem'->new("Qt4\ Designer");
    $app_qt4_designer_5706->signal_connect('activate', sub {system "designer\-qt4 &"});
    $app_qt4_designer_5706->set_property('tooltip_text', "Design\ GUIs\ for\ Qt4\ applications");
    $app_qt4_designer_5706->set_image('Gtk2::Image'->new_from_icon_name("designer\-qt4",q{menu}));
    $apps->append($app_qt4_designer_5706);
}
{
    my $app_qt4_linguist_2616 = 'Gtk2::ImageMenuItem'->new("Qt4\ Linguist");
    $app_qt4_linguist_2616->signal_connect('activate', sub {system "linguist\-qt4 &"});
    $app_qt4_linguist_2616->set_property('tooltip_text', "Add\ translations\ to\ Qt4\ applications");
    $app_qt4_linguist_2616->set_image('Gtk2::Image'->new_from_icon_name("linguist\-qt4",q{menu}));
    $apps->append($app_qt4_linguist_2616);
}
{
    my $app_qt4_qdbusviewer_7449 = 'Gtk2::ImageMenuItem'->new("Qt4\ QDbusViewer");
    $app_qt4_qdbusviewer_7449->signal_connect('activate', sub {system "qdbusviewer\-qt4 &"});
    $app_qt4_qdbusviewer_7449->set_property('tooltip_text', "Debug\ D\-Bus\ applications");
    $app_qt4_qdbusviewer_7449->set_image('Gtk2::Image'->new_from_icon_name("qdbusviewer\-qt4",q{menu}));
    $apps->append($app_qt4_qdbusviewer_7449);
}
    $category_2->set_submenu($apps);
    $menu->append($category_2);
}

    # # # # # # # # # # # # # # # # # # # # GRAPHICS # # # # # # # # # # # # # # # # # # # # 
{
    my $apps = 'Gtk2::Menu'->new;
    my $category_3 = 'Gtk2::ImageMenuItem'->new("Graphics");
    $category_3->set_image('Gtk2::Image'->new_from_icon_name("applications\-graphics",q{menu}));
{
    my $app_feh_6718 = 'Gtk2::ImageMenuItem'->new("Feh");
    $app_feh_6718->signal_connect('activate', sub {system "feh &"});
    $app_feh_6718->set_property('tooltip_text', "Fast\ Imlib2\-based\ Image\ Viewer");
    $app_feh_6718->set_image('Gtk2::Image'->new_from_pixbuf('Gtk2::Gdk::Pixbuf'->new_from_file_at_size("\/usr\/share\/feh\/images\/feh\.png",16,16)));
    $apps->append($app_feh_6718);
}
{
    my $app_geeqie_1764 = 'Gtk2::ImageMenuItem'->new("Geeqie");
    $app_geeqie_1764->signal_connect('activate', sub {system "geeqie\ \-r &"});
    $app_geeqie_1764->set_property('tooltip_text', "View\ and\ manage\ images");
    $app_geeqie_1764->set_image('Gtk2::Image'->new_from_icon_name("geeqie",q{menu}));
    $apps->append($app_geeqie_1764);
}
{
    my $app_gnu_image_manipulation_program_1287 = 'Gtk2::ImageMenuItem'->new("GNU\ Image\ Manipulation\ Program");
    $app_gnu_image_manipulation_program_1287->signal_connect('activate', sub {system "gimp\-2\.8 &"});
    $app_gnu_image_manipulation_program_1287->set_property('tooltip_text', "Create\ images\ and\ edit\ photographs");
    $app_gnu_image_manipulation_program_1287->set_image('Gtk2::Image'->new_from_icon_name("gimp",q{menu}));
    $apps->append($app_gnu_image_manipulation_program_1287);
}
{
    my $app_viewnior_3449 = 'Gtk2::ImageMenuItem'->new("Viewnior");
    $app_viewnior_3449->signal_connect('activate', sub {system "viewnior &"});
    $app_viewnior_3449->set_property('tooltip_text', "Elegant\ Image\ Viewer");
    $app_viewnior_3449->set_image('Gtk2::Image'->new_from_icon_name("viewnior",q{menu}));
    $apps->append($app_viewnior_3449);
}
    $category_3->set_submenu($apps);
    $menu->append($category_3);
}

    # # # # # # # # # # # # # # # # # # # # MULTIMEDIA # # # # # # # # # # # # # # # # # # # # 
{
    my $apps = 'Gtk2::Menu'->new;
    my $category_4 = 'Gtk2::ImageMenuItem'->new("Multimedia");
    $category_4->set_image('Gtk2::Image'->new_from_icon_name("applications\-multimedia",q{menu}));
{
    my $app_audacity_3487 = 'Gtk2::ImageMenuItem'->new("Audacity");
    $app_audacity_3487->signal_connect('activate', sub {system "audacity &"});
    $app_audacity_3487->set_property('tooltip_text', "Record\ and\ edit\ audio\ files");
    $app_audacity_3487->set_image('Gtk2::Image'->new_from_icon_name("audacity",q{menu}));
    $apps->append($app_audacity_3487);
}
{
    my $app_gtk_youtube_viewer_7441 = 'Gtk2::ImageMenuItem'->new("GTK\ Youtube\ Viewer");
    $app_gtk_youtube_viewer_7441->signal_connect('activate', sub {system "gtk\-youtube\-viewer &"});
    $app_gtk_youtube_viewer_7441->set_property('tooltip_text', "A\ Gtk2\ application\ to\ search\ and\ play\ Youtube\ videos\ with\ MPlayer\.");
    $app_gtk_youtube_viewer_7441->set_image('Gtk2::Image'->new_from_icon_name("gtk\-youtube\-viewer",q{menu}));
    $apps->append($app_gtk_youtube_viewer_7441);
}
{
    my $app_qt_v4l2_test_utility_1276 = 'Gtk2::ImageMenuItem'->new("QT\ V4L2\ test\ Utility");
    $app_qt_v4l2_test_utility_1276->signal_connect('activate', sub {system "qv4l2 &"});
    $app_qt_v4l2_test_utility_1276->set_property('tooltip_text', "Allow\ testing\ Video4Linux\ devices");
    $app_qt_v4l2_test_utility_1276->set_image('Gtk2::Image'->new_from_icon_name("qv4l2",q{menu}));
    $apps->append($app_qt_v4l2_test_utility_1276);
}
{
    my $app_qwinff_4269 = 'Gtk2::ImageMenuItem'->new("QWinFF");
    $app_qwinff_4269->signal_connect('activate', sub {system "qwinff &"});
    $app_qwinff_4269->set_property('tooltip_text', "Convert\ between\ media\ file\ formats");
    $app_qwinff_4269->set_image('Gtk2::Image'->new_from_icon_name("qwinff",q{menu}));
    $apps->append($app_qwinff_4269);
}
{
    my $app_vlc_media_player_5890 = 'Gtk2::ImageMenuItem'->new("VLC\ media\ player");
    $app_vlc_media_player_5890->signal_connect('activate', sub {system "\/usr\/bin\/vlc &"});
    $app_vlc_media_player_5890->set_property('tooltip_text', "Read\,\ capture\,\ broadcast\ your\ multimedia\ streams");
    $app_vlc_media_player_5890->set_image('Gtk2::Image'->new_from_icon_name("vlc",q{menu}));
    $apps->append($app_vlc_media_player_5890);
}
    $category_4->set_submenu($apps);
    $menu->append($category_4);
}

    # # # # # # # # # # # # # # # # # # # # NETWORK # # # # # # # # # # # # # # # # # # # # 
{
    my $apps = 'Gtk2::Menu'->new;
    my $category_5 = 'Gtk2::ImageMenuItem'->new("Network");
    $category_5->set_image('Gtk2::Image'->new_from_icon_name("applications\-internet",q{menu}));
{
    my $app_deluge_6616 = 'Gtk2::ImageMenuItem'->new("Deluge");
    $app_deluge_6616->signal_connect('activate', sub {system "deluge\-gtk &"});
    $app_deluge_6616->set_property('tooltip_text', "Download\ and\ share\ files\ over\ BitTorrent");
    $app_deluge_6616->set_image('Gtk2::Image'->new_from_icon_name("deluge",q{menu}));
    $apps->append($app_deluge_6616);
}
{
    my $app_gftp_4124 = 'Gtk2::ImageMenuItem'->new("gFTP");
    $app_gftp_4124->signal_connect('activate', sub {system "gftp &"});
    $app_gftp_4124->set_property('tooltip_text', "Download\ and\ upload\ files\ using\ multiple\ file\ transfer\ protocols");
    $app_gftp_4124->set_image('Gtk2::Image'->new_from_icon_name("gftp",q{menu}));
    $apps->append($app_gftp_4124);
}
{
    my $app_google_chrome_7959 = 'Gtk2::ImageMenuItem'->new("Google\ Chrome");
    $app_google_chrome_7959->signal_connect('activate', sub {system "\/opt\/google\/chrome\/google\-chrome &"});
    $app_google_chrome_7959->set_property('tooltip_text', "Access\ the\ Internet");
    $app_google_chrome_7959->set_image('Gtk2::Image'->new_from_icon_name("google\-chrome",q{menu}));
    $apps->append($app_google_chrome_7959);
}
{
    my $app_luakit_8099 = 'Gtk2::ImageMenuItem'->new("Luakit");
    $app_luakit_8099->signal_connect('activate', sub {system "luakit &"});
    $app_luakit_8099->set_property('tooltip_text', "Fast\,\ small\,\ webkit\ based\ micro\-browser\ extensible\ by\ Lua");
    $app_luakit_8099->set_image('Gtk2::Image'->new_from_icon_name("luakit",q{menu}));
    $apps->append($app_luakit_8099);
}
    $category_5->set_submenu($apps);
    $menu->append($category_5);
}

    # # # # # # # # # # # # # # # # # # # # OFFICE # # # # # # # # # # # # # # # # # # # # 
{
    my $apps = 'Gtk2::Menu'->new;
    my $category_6 = 'Gtk2::ImageMenuItem'->new("Office");
    $category_6->set_image('Gtk2::Image'->new_from_icon_name("applications\-office",q{menu}));
{
    my $app_libreoffice_9604 = 'Gtk2::ImageMenuItem'->new("LibreOffice");
    $app_libreoffice_9604->signal_connect('activate', sub {system "libreoffice &"});
    $app_libreoffice_9604->set_property('tooltip_text', "The\ office\ productivity\ suite\ compatible\ to\ the\ open\ and\ standardized\ ODF\ document\ format\.\ Supported\ by\ The\ Document\ Foundation\.");
    $app_libreoffice_9604->set_image('Gtk2::Image'->new_from_icon_name("libreoffice\-startcenter",q{menu}));
    $apps->append($app_libreoffice_9604);
}
{
    my $app_libreoffice_calc_6921 = 'Gtk2::ImageMenuItem'->new("LibreOffice\ Calc");
    $app_libreoffice_calc_6921->signal_connect('activate', sub {system "libreoffice\ \-\-calc &"});
    $app_libreoffice_calc_6921->set_property('tooltip_text', "Perform\ calculations\,\ analyze\ information\ and\ manage\ lists\ in\ spreadsheets\ by\ using\ Calc\.");
    $app_libreoffice_calc_6921->set_image('Gtk2::Image'->new_from_icon_name("libreoffice\-calc",q{menu}));
    $apps->append($app_libreoffice_calc_6921);
}
{
    my $app_libreoffice_impress_8592 = 'Gtk2::ImageMenuItem'->new("LibreOffice\ Impress");
    $app_libreoffice_impress_8592->signal_connect('activate', sub {system "libreoffice\ \-\-impress &"});
    $app_libreoffice_impress_8592->set_property('tooltip_text', "Create\ and\ edit\ presentations\ for\ slideshows\,\ meeting\ and\ Web\ pages\ by\ using\ Impress\.");
    $app_libreoffice_impress_8592->set_image('Gtk2::Image'->new_from_icon_name("libreoffice\-impress",q{menu}));
    $apps->append($app_libreoffice_impress_8592);
}
{
    my $app_libreoffice_writer_5526 = 'Gtk2::ImageMenuItem'->new("LibreOffice\ Writer");
    $app_libreoffice_writer_5526->signal_connect('activate', sub {system "libreoffice\ \-\-writer &"});
    $app_libreoffice_writer_5526->set_property('tooltip_text', "Create\ and\ edit\ text\ and\ graphics\ in\ letters\,\ reports\,\ documents\ and\ Web\ pages\ by\ using\ Writer\.");
    $app_libreoffice_writer_5526->set_image('Gtk2::Image'->new_from_icon_name("libreoffice\-writer",q{menu}));
    $apps->append($app_libreoffice_writer_5526);
}
    $category_6->set_submenu($apps);
    $menu->append($category_6);
}

    # # # # # # # # # # # # # # # # # # # # SETTINGS # # # # # # # # # # # # # # # # # # # # 
{
    my $apps = 'Gtk2::Menu'->new;
    my $category_7 = 'Gtk2::ImageMenuItem'->new("Settings");
    $category_7->set_image('Gtk2::Image'->new_from_icon_name("applications\-accessories",q{menu}));
{
    my $app_adobe_flash_player_9460 = 'Gtk2::ImageMenuItem'->new("Adobe\ Flash\ Player");
    $app_adobe_flash_player_9460->signal_connect('activate', sub {system "flash\-player\-properties &"});
    $app_adobe_flash_player_9460->set_property('tooltip_text', "Preferences\ for\ Adobe\ Flash\ Player");
    $app_adobe_flash_player_9460->set_image('Gtk2::Image'->new_from_icon_name("flash\-player\-properties",q{menu}));
    $apps->append($app_adobe_flash_player_9460);
}
{
    my $app_customize_look_and_feel_7176 = 'Gtk2::ImageMenuItem'->new("Customize\ Look\ and\ Feel");
    $app_customize_look_and_feel_7176->signal_connect('activate', sub {system "lxappearance &"});
    $app_customize_look_and_feel_7176->set_property('tooltip_text', "Customizes\ look\ and\ feel\ of\ your\ desktop\ and\ applications");
    $app_customize_look_and_feel_7176->set_image('Gtk2::Image'->new_from_icon_name("preferences\-desktop\-theme",q{menu}));
    $apps->append($app_customize_look_and_feel_7176);
}
{
    my $app_nvidia_x_server_settings_5993 = 'Gtk2::ImageMenuItem'->new("NVIDIA\ X\ Server\ Settings");
    $app_nvidia_x_server_settings_5993->signal_connect('activate', sub {system "\/usr\/bin\/nvidia\-settings &"});
    $app_nvidia_x_server_settings_5993->set_property('tooltip_text', "Configure\ NVIDIA\ X\ Server\ Settings");
    $app_nvidia_x_server_settings_5993->set_image('Gtk2::Image'->new_from_pixbuf('Gtk2::Gdk::Pixbuf'->new_from_file_at_size("\/usr\/share\/pixmaps\/nvidia\-settings\.png",16,16)));
    $apps->append($app_nvidia_x_server_settings_5993);
}
{
    my $app_openbox_configuration_manager_3660 = 'Gtk2::ImageMenuItem'->new("Openbox\ Configuration\ Manager");
    $app_openbox_configuration_manager_3660->signal_connect('activate', sub {system "obconf &"});
    $app_openbox_configuration_manager_3660->set_property('tooltip_text', "Openbox\ configuration\ manager");
    $app_openbox_configuration_manager_3660->set_image('Gtk2::Image'->new_from_icon_name("obconf",q{menu}));
    $apps->append($app_openbox_configuration_manager_3660);
}
{
    my $app_panel_tint2_8187 = 'Gtk2::ImageMenuItem'->new("Panel\ tint2");
    $app_panel_tint2_8187->signal_connect('activate', sub {system "tint2conf &"});
    $app_panel_tint2_8187->set_property('tooltip_text', "Customize\ the\ panel\ settings");
    $app_panel_tint2_8187->set_image('Gtk2::Image'->new_from_icon_name("tint2conf",q{menu}));
    $apps->append($app_panel_tint2_8187);
}
{
    my $app_preferred_applications_8443 = 'Gtk2::ImageMenuItem'->new("Preferred\ Applications");
    $app_preferred_applications_8443->signal_connect('activate', sub {system "libfm\-pref\-apps &"});
    $app_preferred_applications_8443->set_property('tooltip_text', "");
    $app_preferred_applications_8443->set_image('Gtk2::Image'->new_from_icon_name("preferences\-desktop",q{menu}));
    $apps->append($app_preferred_applications_8443);
}
    $category_7->set_submenu($apps);
    $menu->append($category_7);
}

    # # # # # # # # # # # # # # # # # # # # SYSTEM # # # # # # # # # # # # # # # # # # # # 
{
    my $apps = 'Gtk2::Menu'->new;
    my $category_8 = 'Gtk2::ImageMenuItem'->new("System");
    $category_8->set_image('Gtk2::Image'->new_from_icon_name("applications\-system",q{menu}));
{
    my $app_bleachbit_6299 = 'Gtk2::ImageMenuItem'->new("BleachBit");
    $app_bleachbit_6299->signal_connect('activate', sub {system "bleachbit &"});
    $app_bleachbit_6299->set_property('tooltip_text', "Free\ space\ and\ maintain\ privacy");
    $app_bleachbit_6299->set_image('Gtk2::Image'->new_from_icon_name("bleachbit",q{menu}));
    $apps->append($app_bleachbit_6299);
}
{
    my $app_htop_3362 = 'Gtk2::ImageMenuItem'->new("Htop");
    $app_htop_3362->signal_connect('activate', sub {system "sakura\ \-e\ \'htop\' &"});
    $app_htop_3362->set_property('tooltip_text', "Show\ System\ Processes");
    $app_htop_3362->set_image('Gtk2::Image'->new_from_icon_name("htop",q{menu}));
    $apps->append($app_htop_3362);
}
{
    my $app_task_manager_6376 = 'Gtk2::ImageMenuItem'->new("Task\ Manager");
    $app_task_manager_6376->signal_connect('activate', sub {system "lxtask &"});
    $app_task_manager_6376->set_property('tooltip_text', "Manage\ running\ processes");
    $app_task_manager_6376->set_image('Gtk2::Image'->new_from_icon_name("utilities\-system\-monitor",q{menu}));
    $apps->append($app_task_manager_6376);
}
{
    my $app_uxterm_7821 = 'Gtk2::ImageMenuItem'->new("UXTerm");
    $app_uxterm_7821->signal_connect('activate', sub {system "uxterm &"});
    $app_uxterm_7821->set_property('tooltip_text', "standard\ terminal\ emulator\ for\ the\ X\ window\ system");
    $app_uxterm_7821->set_image('Gtk2::Image'->new_from_icon_name("xterm\-color_48x48",q{menu}));
    $apps->append($app_uxterm_7821);
}
{
    my $app_xterm_9189 = 'Gtk2::ImageMenuItem'->new("XTerm");
    $app_xterm_9189->signal_connect('activate', sub {system "xterm &"});
    $app_xterm_9189->set_property('tooltip_text', "standard\ terminal\ emulator\ for\ the\ X\ window\ system");
    $app_xterm_9189->set_image('Gtk2::Image'->new_from_icon_name("xterm\-color_48x48",q{menu}));
    $apps->append($app_xterm_9189);
}
    $category_8->set_submenu($apps);
    $menu->append($category_8);
}

    # # # # # # # # # # # # # # # # # # # # MENUTRAY # # # # # # # # # # # # # # # # # # # # 
{
    my $apps = 'Gtk2::Menu'->new;
    my $category_9 = 'Gtk2::ImageMenuItem'->new("Menutray");
    $category_9->set_image('Gtk2::Image'->new_from_icon_name("preferences\-desktop",q{menu}));
{
    my $app_edit_menutray_s_config_2898 = 'Gtk2::ImageMenuItem'->new("Edit\ menutray\'s\ config");
    $app_edit_menutray_s_config_2898->signal_connect('activate', sub {system "geany\ \/home\/swampyx\/\.config\/menutray\/config\.pl &"});
    $app_edit_menutray_s_config_2898->set_property('tooltip_text', "");
    $app_edit_menutray_s_config_2898->set_image('Gtk2::Image'->new_from_icon_name("preferences\-desktop",q{menu}));
    $apps->append($app_edit_menutray_s_config_2898);
}
{
    my $app_edit_menutray_s_menu_9348 = 'Gtk2::ImageMenuItem'->new("Edit\ menutray\'s\ menu");
    $app_edit_menutray_s_menu_9348->signal_connect('activate', sub {system "geany\ \/home\/swampyx\/\.config\/menutray\/menu\.pl &"});
    $app_edit_menutray_s_menu_9348->set_property('tooltip_text', "");
    $app_edit_menutray_s_menu_9348->set_image('Gtk2::Image'->new_from_icon_name("preferences\-desktop",q{menu}));
    $apps->append($app_edit_menutray_s_menu_9348);
}
{
    my $app_edit_menutray_s_schema_5937 = 'Gtk2::ImageMenuItem'->new("Edit\ menutray\'s\ schema");
    $app_edit_menutray_s_schema_5937->signal_connect('activate', sub {system "geany\ \/home\/swampyx\/\.config\/menutray\/schema\.pl &"});
    $app_edit_menutray_s_schema_5937->set_property('tooltip_text', "");
    $app_edit_menutray_s_schema_5937->set_image('Gtk2::Image'->new_from_icon_name("preferences\-desktop",q{menu}));
    $apps->append($app_edit_menutray_s_schema_5937);
}
    $category_9->set_submenu($apps);
    $menu->append($category_9);
}

    $menu->append('Gtk2::SeparatorMenuItem'->new);
{
    my $regenerate = 'Gtk2::ImageMenuItem'->new("Regenerate");
    $regenerate->set_property('tooltip_text', "Regenerate\ this\ menu\.");
    $regenerate->set_image('Gtk2::Image'->new_from_icon_name("gtk\-refresh",q{menu}));
    $regenerate->signal_connect('activate', sub {system "\/usr\/bin\/perl\ \\\/usr\\\/bin\\\/menutray\ \-i &"; 'Gtk2'->main_quit; exit});
    $menu->append($regenerate);
}
{
    my $quit = 'Gtk2::ImageMenuItem'->new("Exit");
    $quit->set_property('tooltip_text', "Close\ this\ application\.");
    $quit->set_image('Gtk2::Image'->new_from_icon_name("gtk\-quit",q{menu}));
    $quit->signal_connect('activate', sub { Gtk2->main_quit; exit });
    $menu->append($quit);
}
    $menu->show_all;
    return 1;
}
'Gtk2'->main;
